openapi: 3.0.0
info:
  description: This API receives hardware status reading from Crypto mining rig
  version: "1.0.0"
  title: Mining rig API
  contact:
    email: dgao12@my.bcit.ca
paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets fan speed and temperature processsed statistics
      responses:
        '200':
          description: Successfully returned a list of events
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ReadingStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    ReadingStats:
      required:
        - avg_core_temp
        - avg_shell_temp
        - num_core_temp
        - num_shell_temp
        - num_fan_speed
        - avg_fan_speed
      properties:
        avg_fan_speed:
          type: number
          example: 20.00
          format: double
        num_fan_speed:
          type: integer
          example: 2000
        avg_core_temp:
          type: number
          example: 20.00
          format: double
        avg_shell_temp:
          type: number
          example: 20.00
          format: double
        num_core_temp:
          type: integer
          example: 60
        num_shell_temp:
          type: integer
          example: 60
      type: object